# Generated by Django 4.0.1 on 2022-01-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='tournamtent',
            new_name='tournament',
        ),
    ]
